#include "broad_phase_dx.h"
#include "dx_common.h"
#include "brute_force_shader.h"

#include <string.h>

struct dx_state_brute_force {
	ID3D12RootSignature* root_sig;
	ID3D12PipelineState* pso;
	ID3D12Resource* up_zero;
	size_t up_zero_size;
};

extern "C" dx_state_brute_force* dx_state_brute_force_create(dx_shared_state* sh) {
	dx_state_brute_force* s = (dx_state_brute_force*)calloc(1, sizeof(dx_state_brute_force));

	// Define the 5 parameters matching the HLSL registers
	D3D12_ROOT_PARAMETER root_params[5] = {};

	// Parameter 0: Constants (register b0)
	root_params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	root_params[0].Constants.ShaderRegister = 0;
	root_params[0].Constants.RegisterSpace = 0;
	root_params[0].Constants.Num32BitValues = 3;
	root_params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 1: rigids SRV (register t0)
	root_params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[1].Descriptor.ShaderRegister = 0;
	root_params[1].Descriptor.RegisterSpace = 0;
	root_params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 2: statics SRV (register t1)
	root_params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[2].Descriptor.ShaderRegister = 1;
	root_params[2].Descriptor.RegisterSpace = 0;
	root_params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 3: pairs UAV (register u0)
	root_params[3].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[3].Descriptor.ShaderRegister = 0;
	root_params[3].Descriptor.RegisterSpace = 0;
	root_params[3].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 4: pair_count UAV (register u1)
	root_params[4].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[4].Descriptor.ShaderRegister = 1;
	root_params[4].Descriptor.RegisterSpace = 0;
	root_params[4].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	D3D12_ROOT_SIGNATURE_DESC rs_desc = {};
	rs_desc.NumParameters = 5;
	rs_desc.pParameters = root_params;
	rs_desc.NumStaticSamplers = 0;
	rs_desc.pStaticSamplers = nullptr;
	rs_desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob* signature = nullptr;
	ID3DBlob* error = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(
		&rs_desc, D3D_ROOT_SIGNATURE_VERSION_1, &signature, &error);
		
	if (FAILED(hr)) {
		if (error) {
			fprintf(stderr, "[dx12] Root Signature Error: %s\n", 
					(char*)error->GetBufferPointer());
			error->Release();
		}
		return s;
	}

	DX_CHECK(sh->device->CreateRootSignature(
		0, signature->GetBufferPointer(), signature->GetBufferSize(), 
		IID_PPV_ARGS(&s->root_sig)));
	signature->Release();

	// Create the Pipeline State Object using the byte array generated by dxc
	D3D12_COMPUTE_PIPELINE_STATE_DESC pso_desc = {};
	pso_desc.pRootSignature = s->root_sig;
	pso_desc.CS.pShaderBytecode = brute_force_shader;
	pso_desc.CS.BytecodeLength = sizeof(brute_force_shader);
	pso_desc.NodeMask = 0;
	pso_desc.Flags = D3D12_PIPELINE_STATE_FLAG_NONE;

	DX_CHECK(sh->device->CreateComputePipelineState(&pso_desc, IID_PPV_ARGS(&s->pso)));

	// Allocate a persistent 4-byte buffer containing 0 to quickly reset the atomic counter
	ensure_dx_buffer(sh->device, &s->up_zero, &s->up_zero_size, 1, sizeof(uint32_t),
					 D3D12_HEAP_TYPE_UPLOAD, D3D12_RESOURCE_STATE_GENERIC_READ, 
					 D3D12_RESOURCE_FLAG_NONE);
	void* p_zero;
	D3D12_RANGE read_range = {0, 0};
	s->up_zero->Map(0, &read_range, &p_zero);
	*(uint32_t*)p_zero = 0;
	s->up_zero->Unmap(0, nullptr);

	return s;
}

extern "C" void dx_state_brute_force_destroy(dx_state_brute_force* s) {
	if (!s) return;
	if (s->up_zero) s->up_zero->Release();
	if (s->pso) s->pso->Release();
	if (s->root_sig) s->root_sig->Release();
	free(s);
}

extern "C" dx_pair* dx_broad_phase_brute_force(dx_shared_state* sh,
												dx_state_brute_force* state,
												const dx_aabb* rigids, int rigid_count,
												const dx_aabb* statics, int static_count,
												bool statics_changed, size_t* out_count) {
	*out_count = 0;
	if (rigid_count == 0) return nullptr;

	// Upload Data via Upload Heaps
	ensure_dx_buffer(sh->device, &sh->up_rigids, &sh->up_rigids_size, rigid_count, sizeof(dx_aabb),
					 D3D12_HEAP_TYPE_UPLOAD, D3D12_RESOURCE_STATE_GENERIC_READ, 
					 D3D12_RESOURCE_FLAG_NONE);
	ensure_dx_buffer(sh->device, &sh->d_rigids, &sh->d_rigids_size, rigid_count, sizeof(dx_aabb),
					 D3D12_HEAP_TYPE_DEFAULT, D3D12_RESOURCE_STATE_COMMON, 
					 D3D12_RESOURCE_FLAG_NONE);
	
	void* mapped = nullptr;
	D3D12_RANGE read_range = {0, 0};
	sh->up_rigids->Map(0, &read_range, &mapped);
	memcpy(mapped, rigids, rigid_count * sizeof(dx_aabb));
	sh->up_rigids->Unmap(0, nullptr);

	if (statics_changed && static_count > 0) {
		ensure_dx_buffer(sh->device, &sh->up_statics, &sh->up_statics_size, static_count, sizeof(dx_aabb),
						 D3D12_HEAP_TYPE_UPLOAD, D3D12_RESOURCE_STATE_GENERIC_READ, 
						 D3D12_RESOURCE_FLAG_NONE);
		ensure_dx_buffer(sh->device, &sh->d_statics, &sh->d_statics_size, static_count, sizeof(dx_aabb),
						 D3D12_HEAP_TYPE_DEFAULT, D3D12_RESOURCE_STATE_COMMON, 
						 D3D12_RESOURCE_FLAG_NONE);
						 
		sh->up_statics->Map(0, &read_range, &mapped);
		memcpy(mapped, statics, static_count * sizeof(dx_aabb));
		sh->up_statics->Unmap(0, nullptr);
	}

	// Heuristic output size: We probably won't have more than 8 potential collisions per body.
	// If we actually have more than that, the first run fails and will output the actual required
	// size (count). We then run a second time with the actually required size.
	size_t pairs_needed = sh->d_pairs_size;
	if (pairs_needed < 8 * (rigid_count + static_count))
		pairs_needed = 8 * (rigid_count + static_count);
	if (pairs_needed < 1024) pairs_needed = 1024;

	uint32_t count = 0;
	const int block_size = 256;
	uint32_t grid_size = (rigid_count + block_size - 1) / block_size;

	ensure_dx_buffer(sh->device, &sh->rb_pair_count, &sh->rb_pair_count_size, 1, sizeof(uint32_t),
					 D3D12_HEAP_TYPE_READBACK, D3D12_RESOURCE_STATE_COPY_DEST, 
					 D3D12_RESOURCE_FLAG_NONE);
	ensure_dx_buffer(sh->device, &sh->d_pair_count, &sh->d_pair_count_size, 1, sizeof(uint32_t),
					 D3D12_HEAP_TYPE_DEFAULT, D3D12_RESOURCE_STATE_COMMON, 
					 D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);

	for (int attempt = 0; attempt < 2; ++attempt) {
		ensure_dx_buffer(sh->device, &sh->d_pairs, &sh->d_pairs_size, pairs_needed, sizeof(dx_pair),
						 D3D12_HEAP_TYPE_DEFAULT, D3D12_RESOURCE_STATE_COMMON, 
						 D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);

		uint32_t kernel_max = (sh->d_pairs_size > (size_t)UINT32_MAX) ? UINT32_MAX : (uint32_t)sh->d_pairs_size;

		// --- Record Command List ---
		D3D12_RESOURCE_BARRIER barriers[8] = {};
		int b_idx = 0;
		auto add_transition = [&](ID3D12Resource* res, D3D12_RESOURCE_STATES before, D3D12_RESOURCE_STATES after) {
			if (before == after) return;
			barriers[b_idx].Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
			barriers[b_idx].Flags = D3D12_RESOURCE_BARRIER_FLAG_NONE;
			barriers[b_idx].Transition.pResource = res;
			barriers[b_idx].Transition.Subresource = 0;
			barriers[b_idx].Transition.StateBefore = before;
			barriers[b_idx].Transition.StateAfter = after;
			b_idx++;
		};

		// Transition to COPY_DEST
		add_transition(sh->d_rigids, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_COPY_DEST);
		if (statics_changed && static_count > 0) {
			add_transition(sh->d_statics, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_COPY_DEST);
		}
		add_transition(sh->d_pair_count, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_COPY_DEST);
		if (b_idx > 0) sh->cmd_list->ResourceBarrier(b_idx, barriers);

		// Perform Copies (Host -> Device)
		sh->cmd_list->CopyBufferRegion(sh->d_rigids, 0, sh->up_rigids, 0, rigid_count * sizeof(dx_aabb));
		if (statics_changed && static_count > 0) {
			sh->cmd_list->CopyBufferRegion(sh->d_statics, 0, sh->up_statics, 0, static_count * sizeof(dx_aabb));
		}
		sh->cmd_list->CopyBufferRegion(sh->d_pair_count, 0, state->up_zero, 0, sizeof(uint32_t));

		// Transition to Compute States
		b_idx = 0;
		add_transition(sh->d_rigids, D3D12_RESOURCE_STATE_COPY_DEST, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		if (statics_changed && static_count > 0) {
			add_transition(sh->d_statics, D3D12_RESOURCE_STATE_COPY_DEST, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		} else if (static_count > 0) {
			// Statics weren't copied, so they are still in COMMON from last frame
			add_transition(sh->d_statics, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
		}
		add_transition(sh->d_pair_count, D3D12_RESOURCE_STATE_COPY_DEST, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
		add_transition(sh->d_pairs, D3D12_RESOURCE_STATE_COMMON, D3D12_RESOURCE_STATE_UNORDERED_ACCESS);
		if (b_idx > 0) sh->cmd_list->ResourceBarrier(b_idx, barriers);

		// Dispatch Compute Shader
		sh->cmd_list->SetComputeRootSignature(state->root_sig);
		sh->cmd_list->SetPipelineState(state->pso);
		
		uint32_t constants[3] = { (uint32_t)rigid_count, (uint32_t)static_count, kernel_max };
		sh->cmd_list->SetComputeRoot32BitConstants(0, 3, constants, 0);
		sh->cmd_list->SetComputeRootShaderResourceView(1, sh->d_rigids->GetGPUVirtualAddress());
		if (static_count > 0) {
			sh->cmd_list->SetComputeRootShaderResourceView(2, sh->d_statics->GetGPUVirtualAddress());
		} else {
			// Bind dummy SRV to prevent driver complaints if static_count == 0 (shader ignores it anyway)
			sh->cmd_list->SetComputeRootShaderResourceView(2, sh->d_rigids->GetGPUVirtualAddress());
		}
		sh->cmd_list->SetComputeRootUnorderedAccessView(3, sh->d_pairs->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(4, sh->d_pair_count->GetGPUVirtualAddress());

		sh->cmd_list->Dispatch(grid_size, 1, 1);

		// Readback Counter & Transition back to COMMON
		b_idx = 0;
		add_transition(sh->d_pair_count, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, D3D12_RESOURCE_STATE_COPY_SOURCE);
		if (b_idx > 0) sh->cmd_list->ResourceBarrier(b_idx, barriers);

		sh->cmd_list->CopyBufferRegion(sh->rb_pair_count, 0, sh->d_pair_count, 0, sizeof(uint32_t));

		b_idx = 0;
		add_transition(sh->d_rigids, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE, D3D12_RESOURCE_STATE_COMMON);
		if (static_count > 0) {
			add_transition(sh->d_statics, D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE, D3D12_RESOURCE_STATE_COMMON);
		}
		add_transition(sh->d_pairs, D3D12_RESOURCE_STATE_UNORDERED_ACCESS, D3D12_RESOURCE_STATE_COMMON);
		add_transition(sh->d_pair_count, D3D12_RESOURCE_STATE_COPY_SOURCE, D3D12_RESOURCE_STATE_COMMON);
		if (b_idx > 0) sh->cmd_list->ResourceBarrier(b_idx, barriers);

		dx_execute_and_wait(sh);

		sh->rb_pair_count->Map(0, &read_range, &mapped);
		count = *(uint32_t*)mapped;
		sh->rb_pair_count->Unmap(0, nullptr);

		if (count <= kernel_max) break; // Everything fit.
		pairs_needed = count; // Rerun with the actual count
		statics_changed = false; // Don't copy static bodies again on retry
	}

	// Readback Pairs (if collisions found)
	dx_pair* h_pairs = nullptr;
	if (count > 0) {
		ensure_dx_buffer(sh->device, &sh->rb_pairs, &sh->rb_pairs_size, count, sizeof(dx_pair),
						 D3D12_HEAP_TYPE_READBACK, D3D12_RESOURCE_STATE_COPY_DEST, 
						 D3D12_RESOURCE_FLAG_NONE);
		
		D3D12_RESOURCE_BARRIER barriers[2] = {};
		barriers[0].Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		barriers[0].Transition.pResource = sh->d_pairs;
		barriers[0].Transition.Subresource = 0;
		barriers[0].Transition.StateBefore = D3D12_RESOURCE_STATE_COMMON;
		barriers[0].Transition.StateAfter = D3D12_RESOURCE_STATE_COPY_SOURCE;
		sh->cmd_list->ResourceBarrier(1, barriers);

		sh->cmd_list->CopyBufferRegion(sh->rb_pairs, 0, sh->d_pairs, 0, count * sizeof(dx_pair));

		barriers[0].Transition.StateBefore = D3D12_RESOURCE_STATE_COPY_SOURCE;
		barriers[0].Transition.StateAfter = D3D12_RESOURCE_STATE_COMMON;
		sh->cmd_list->ResourceBarrier(1, barriers);

		dx_execute_and_wait(sh);

		h_pairs = (dx_pair*)malloc(count * sizeof(dx_pair));
		sh->rb_pairs->Map(0, &read_range, &mapped);
		memcpy(h_pairs, mapped, count * sizeof(dx_pair));
		sh->rb_pairs->Unmap(0, nullptr);

		*out_count = count;
	}

	return h_pairs;
}
