#include "broad_phase_dx.h"
#include "brute_force_shader.h"
#include "dx_common.h"
#include "dx_profile.h"

#include <string.h>

struct dx_state_brute_force {
	ID3D12RootSignature* root_sig;
	ID3D12PipelineState* pso;
};

extern "C" dx_state_brute_force* dx_state_brute_force_create(dx_shared_state* sh) {
	dx_state_brute_force* s = (dx_state_brute_force*)calloc(1, sizeof(dx_state_brute_force));

	// Define the 5 parameters matching the HLSL registers
	D3D12_ROOT_PARAMETER root_params[5] = {};

	// Parameter 0: Constants (register b0)
	root_params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	root_params[0].Constants.ShaderRegister = 0;
	root_params[0].Constants.RegisterSpace = 0;
	root_params[0].Constants.Num32BitValues = 3;
	root_params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 1: rigids SRV (register t0)
	root_params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[1].Descriptor.ShaderRegister = 0;
	root_params[1].Descriptor.RegisterSpace = 0;
	root_params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 2: statics SRV (register t1)
	root_params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[2].Descriptor.ShaderRegister = 1;
	root_params[2].Descriptor.RegisterSpace = 0;
	root_params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 3: pairs UAV (register u0)
	root_params[3].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[3].Descriptor.ShaderRegister = 0;
	root_params[3].Descriptor.RegisterSpace = 0;
	root_params[3].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 4: pair_count UAV (register u1)
	root_params[4].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[4].Descriptor.ShaderRegister = 1;
	root_params[4].Descriptor.RegisterSpace = 0;
	root_params[4].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	D3D12_ROOT_SIGNATURE_DESC rs_desc = {};
	rs_desc.NumParameters = 5;
	rs_desc.pParameters = root_params;
	rs_desc.NumStaticSamplers = 0;
	rs_desc.pStaticSamplers = nullptr;
	rs_desc.Flags = D3D12_ROOT_SIGNATURE_FLAG_NONE;

	ID3DBlob* signature = nullptr;
	ID3DBlob* error = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(
		&rs_desc, D3D_ROOT_SIGNATURE_VERSION_1, &signature, &error);
		
	if (FAILED(hr)) {
		if (error) {
			fprintf(stderr, "[dx12] Root Signature Error: %s\n", 
					(char*)error->GetBufferPointer());
			error->Release();
		}
		return s;
	}

	DX_CHECK(sh->device->CreateRootSignature(
		0, signature->GetBufferPointer(), signature->GetBufferSize(), 
		IID_PPV_ARGS(&s->root_sig)));
	signature->Release();

	// Create the Pipeline State Object using the byte array generated by dxc
	D3D12_COMPUTE_PIPELINE_STATE_DESC pso_desc = {};
	pso_desc.pRootSignature = s->root_sig;
	pso_desc.CS.pShaderBytecode = brute_force_shader;
	pso_desc.CS.BytecodeLength = sizeof(brute_force_shader);
	pso_desc.NodeMask = 0;
	pso_desc.Flags = D3D12_PIPELINE_STATE_FLAG_NONE;

	DX_CHECK(sh->device->CreateComputePipelineState(&pso_desc, IID_PPV_ARGS(&s->pso)));

	return s;
}

extern "C" void dx_state_brute_force_destroy(dx_state_brute_force* s) {
	if (!s) return;
	if (s->pso) s->pso->Release();
	if (s->root_sig) s->root_sig->Release();
	free(s);
}

extern "C" dx_pair* dx_broad_phase_brute_force(dx_shared_state* sh, dx_state_brute_force* state,
											   const dx_aabb* rigids, int rigid_count,
											   const dx_aabb* statics, int static_count,
											   bool statics_changed, size_t* out_count) {
	*out_count = 0;
	if (rigid_count == 0) return nullptr;

	// Heuristic output size: We probably won't have more than 8 potential collisions per body.
	// If we actually have more than that, the first run fails and will output the actual required
	// size (count). We then run a second time with the actually required size.
	size_t pairs_needed = sh->d_pairs_size;
	if (pairs_needed < 8 * (rigid_count + static_count))
		pairs_needed = 8 * (rigid_count + static_count);
	if (pairs_needed < 1024) pairs_needed = 1024;

	uint32_t count = 0;
	const int block_size = 256;
	uint32_t grid_size = (rigid_count + block_size - 1) / block_size;
	dx_profile prof = {0};

	for (int attempt = 0; attempt < 2; ++attempt) {
		// Upload data and prepare resources for the compute shader
		dx_shared_begin_pass(sh, rigids, rigid_count, statics, static_count, statics_changed, 
							 pairs_needed, &prof);

		// Compute the maximum capacity using the actual allocated size of the pairs buffer
		uint32_t kernel_max = 
			(sh->d_pairs_size > (size_t)UINT32_MAX) ? UINT32_MAX : (uint32_t)sh->d_pairs_size;

		// Algorithm-specific Dispatch
		sh->cmd_list->SetComputeRootSignature(state->root_sig);
		sh->cmd_list->SetPipelineState(state->pso);
		
		uint32_t constants[3] = { (uint32_t)rigid_count, (uint32_t)static_count, kernel_max };
		sh->cmd_list->SetComputeRoot32BitConstants(0, 3, constants, 0);
		sh->cmd_list->SetComputeRootShaderResourceView(1, sh->d_rigids->GetGPUVirtualAddress());
		if (static_count > 0) {
			sh->cmd_list->SetComputeRootShaderResourceView(2, 
														   sh->d_statics->GetGPUVirtualAddress());
		} else {
			// Bind dummy SRV to prevent driver complaints if static_count == 0
			sh->cmd_list->SetComputeRootShaderResourceView(2, 
														   sh->d_rigids->GetGPUVirtualAddress());
		}
		sh->cmd_list->SetComputeRootUnorderedAccessView(3, sh->d_pairs->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(4, sh->d_pair_count->GetGPUVirtualAddress());

		sh->cmd_list->Dispatch(grid_size, 1, 1);
		
		dx_profile_step(&prof, sh, "kernel");

		// Execute the queue, read back the atomic counter, and revert resources to COMMON
		count = dx_shared_execute_and_get_count(sh, static_count, &prof);

		if (count <= kernel_max) break; 
		
		// Capacity exceeded. Re-run with the exact required capacity.
		pairs_needed = count; 
	}

	dx_pair* h_pairs = nullptr;
	if (count > 0) {
		// Success -> Readback the actual collision pairs
		h_pairs = dx_shared_readback_pairs(sh, count, &prof);
		*out_count = count;
	}

	dx_profile_end(&prof, sh);

	static dx_profile_acc prof_acc;
	static bool prof_init = false;
	if (!prof_init) {
		dx_profile_acc_init(&prof_acc);
		prof_init = true;
	}
	dx_profile_log(&prof, &prof_acc, "dx_naive", 10);

	return h_pairs;
}
