if(NOT EMSCRIPTEN)
	add_subdirectory(falling_cube)
	add_subdirectory(spinning_in_vacuum)
	add_subdirectory(box_stack)
	add_subdirectory(sphere_stack)
	add_subdirectory(sphere_pool)
	add_subdirectory(inelastic_impulse)
	add_subdirectory(benchmark_broadphase)
	add_subdirectory(benchmark_narrowphase)
	add_subdirectory(sparse_islands)

	if(TICS_ENABLE_DEBUG_VIEW)
		add_subdirectory(blick_demo)
		add_subdirectory(frame_dump_renderer)
	endif()
endif()

add_subdirectory(playground)
